addresscalculator:
  build: .
  ports:
   - "5000:5000"
  environment:
    ENV: DEV 
  volumes:
    - ./application:/application
  links:
    - mongo

mongo:
  image: mongo
  ports:
    - "27017:27017"
