addresscalculator:
  build: .
  ports:
   - "5000:5000"
  environment:
    ENV: DEV
    DB_MONGO_NAME: "addresses"
    DB_MONGO_HOST: "mongo"
    DB_MONGO_PORT: "27017"
  volumes:
    - ./application:/application
  links:
    - mongo

mongo:
  image: mongo
  ports:
    - "27017:27017"
